/**
* This program is free software, you can redistribute it and/or modify.
* Copyright (c) 2026 Huawei Technologies Co., Ltd.
* This file is a part of the CANN Open Software.
* Licensed under CANN Open Software License Agreement Version 2.0 (the "License").
* Please refer to the License for details. You may not use this file except in compliance with the License.
* THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING
* BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. See LICENSE in the root of
* the software repository for the full text of the License.
*/

/*!
* \file catlass_dynamic_matmul_tiling_key.h
* \brief catlass_dynamic_matmul tiling key declare
*/

#ifndef __CATLASS_DYNAMIC_MATMUL_TILING_KEY_H__
#define __CATLASS_DYNAMIC_MATMUL_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

// data type
#define DEFINED_DT_FLOAT16 1
#define DEFINED_DT_BF16 27

// kernel type
#define COMMON_MATMUL 0
#define SMALL_MATMUL 1
#define PADDING_MATMUL 2
#define MULTICORE_SPLITK_MATMUL 3
#define STREAMK_MATMUL 4
#define NO_PADDING_SINGLECORE_SPLITK_MATMUL 5
#define SINGLECORE_SPLITK_SMALL_MATMUL 6
#define SINGLECORE_SPLITK_KLOOP_OUTER_MATMUL 7
#define SINGLECORE_SPLITK_KLOOP_MIDDLE_MATMUL 8
#define AIV_MATMUL 9

// padding tag
#define DEFINED_PADDING_NONE 0
#define DEFINED_PADDING_ND 1
#define DEFINED_PADDING_BLOCK_ND 2
#define DEFINED_PADDING_NZ 3

// layout tag
#define DEFINED_ROW_MAJOR 0
#define DEFINED_COLUMN_MAJOR 1

// dispatch policy tag
#define MATMUL_AIV_DEFAULT 0
#define MATMUL_AIV_SIMPLE 1
#define MATMUL_AIV_TRANS 2

ASCENDC_TPL_ARGS_DECL(
    CatlassDynamicMatmul,
    ASCENDC_TPL_UINT_DECL(DATATYPE_IN, ASCENDC_TPL_8_BW, ASCENDC_TPL_UI_LIST, DEFINED_DT_FLOAT16, DEFINED_DT_BF16),
    ASCENDC_TPL_UINT_DECL(DATATYPE_OUT, ASCENDC_TPL_8_BW, ASCENDC_TPL_UI_LIST, DEFINED_DT_FLOAT16, DEFINED_DT_BF16),
    ASCENDC_TPL_UINT_DECL(KERNEL_TYPE, ASCENDC_TPL_8_BW, ASCENDC_TPL_UI_LIST,
                          COMMON_MATMUL, SMALL_MATMUL, PADDING_MATMUL, MULTICORE_SPLITK_MATMUL, STREAMK_MATMUL,
                          NO_PADDING_SINGLECORE_SPLITK_MATMUL, SINGLECORE_SPLITK_SMALL_MATMUL, SINGLECORE_SPLITK_KLOOP_OUTER_MATMUL,
                          SINGLECORE_SPLITK_KLOOP_MIDDLE_MATMUL, AIV_MATMUL),
    ASCENDC_TPL_UINT_DECL(PADDING_TAGA, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
                          DEFINED_PADDING_NONE, DEFINED_PADDING_ND, DEFINED_PADDING_BLOCK_ND, DEFINED_PADDING_NZ),
    ASCENDC_TPL_UINT_DECL(PADDING_TAGB, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
                          DEFINED_PADDING_NONE, DEFINED_PADDING_ND, DEFINED_PADDING_BLOCK_ND, DEFINED_PADDING_NZ),
    ASCENDC_TPL_UINT_DECL(PADDING_TAGC, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
                          DEFINED_PADDING_NONE, DEFINED_PADDING_ND, DEFINED_PADDING_BLOCK_ND, DEFINED_PADDING_NZ),
    ASCENDC_TPL_UINT_DECL(LAYOUT_TAGA, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
    ASCENDC_TPL_UINT_DECL(LAYOUT_TAGB, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
    ASCENDC_TPL_UINT_DECL(LAYOUT_TAGC, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
    ASCENDC_TPL_UINT_DECL(DISPATCH_POLICY_TAG, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
                          MATMUL_AIV_DEFAULT, MATMUL_AIV_SIMPLE, MATMUL_AIV_TRANS),
);

ASCENDC_TPL_SEL(
    // common matmul
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),
        ASCENDC_TPL_UINT_SEL(DATATYPE_IN, ASCENDC_TPL_UI_LIST, DEFINED_DT_FLOAT16, DEFINED_DT_BF16),
        ASCENDC_TPL_UINT_SEL(DATATYPE_OUT, ASCENDC_TPL_UI_LIST, DEFINED_DT_FLOAT16, DEFINED_DT_BF16),
        ASCENDC_TPL_UINT_SEL(KERNEL_TYPE, ASCENDC_TPL_UI_LIST, COMMON_MATMUL),
        ASCENDC_TPL_UINT_SEL(PADDING_TAGA, ASCENDC_TPL_UI_LIST, DEFINED_PADDING_NONE),
        ASCENDC_TPL_UINT_SEL(PADDING_TAGB, ASCENDC_TPL_UI_LIST, DEFINED_PADDING_NONE),
        ASCENDC_TPL_UINT_SEL(PADDING_TAGC, ASCENDC_TPL_UI_LIST, DEFINED_PADDING_NONE),
        ASCENDC_TPL_UINT_SEL(LAYOUT_TAGA, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
        ASCENDC_TPL_UINT_SEL(LAYOUT_TAGB, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
        ASCENDC_TPL_UINT_SEL(LAYOUT_TAGC, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
        ASCENDC_TPL_UINT_SEL(DISPATCH_POLICY_TAG, ASCENDC_TPL_UI_LIST, MATMUL_AIV_DEFAULT),
    ),
    // small matmul
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),
        ASCENDC_TPL_UINT_SEL(DATATYPE_IN, ASCENDC_TPL_UI_LIST, DEFINED_DT_FLOAT16, DEFINED_DT_BF16),
        ASCENDC_TPL_UINT_SEL(DATATYPE_OUT, ASCENDC_TPL_UI_LIST, DEFINED_DT_FLOAT16, DEFINED_DT_BF16),
        ASCENDC_TPL_UINT_SEL(KERNEL_TYPE, ASCENDC_TPL_UI_LIST, SMALL_MATMUL),
        ASCENDC_TPL_UINT_SEL(PADDING_TAGA, ASCENDC_TPL_UI_LIST, DEFINED_PADDING_NONE),
        ASCENDC_TPL_UINT_SEL(PADDING_TAGB, ASCENDC_TPL_UI_LIST, DEFINED_PADDING_NONE),
        ASCENDC_TPL_UINT_SEL(PADDING_TAGC, ASCENDC_TPL_UI_LIST, DEFINED_PADDING_NONE),
        ASCENDC_TPL_UINT_SEL(LAYOUT_TAGA, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
        ASCENDC_TPL_UINT_SEL(LAYOUT_TAGB, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
        ASCENDC_TPL_UINT_SEL(LAYOUT_TAGC, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
        ASCENDC_TPL_UINT_SEL(DISPATCH_POLICY_TAG, ASCENDC_TPL_UI_LIST, MATMUL_AIV_DEFAULT),
    ),
    // padding matmul
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(DATATYPE_IN, ASCENDC_TPL_UI_LIST, DEFINED_DT_FLOAT16, DEFINED_DT_BF16),
        ASCENDC_TPL_UINT_SEL(DATATYPE_OUT, ASCENDC_TPL_UI_LIST, DEFINED_DT_FLOAT16, DEFINED_DT_BF16),
        ASCENDC_TPL_UINT_SEL(KERNEL_TYPE, ASCENDC_TPL_UI_LIST, PADDING_MATMUL),
        ASCENDC_TPL_UINT_SEL(PADDING_TAGA, ASCENDC_TPL_UI_LIST, DEFINED_PADDING_NONE, DEFINED_PADDING_NZ),
        ASCENDC_TPL_UINT_SEL(PADDING_TAGB, ASCENDC_TPL_UI_LIST, DEFINED_PADDING_NONE, DEFINED_PADDING_NZ),
        ASCENDC_TPL_UINT_SEL(PADDING_TAGC, ASCENDC_TPL_UI_LIST, DEFINED_PADDING_NONE, DEFINED_PADDING_ND),
        ASCENDC_TPL_UINT_SEL(LAYOUT_TAGA, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
        ASCENDC_TPL_UINT_SEL(LAYOUT_TAGB, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
        ASCENDC_TPL_UINT_SEL(LAYOUT_TAGC, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
        ASCENDC_TPL_UINT_SEL(DISPATCH_POLICY_TAG, ASCENDC_TPL_UI_LIST, MATMUL_AIV_DEFAULT),
    ),
    // multicore splitk matmul
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(DATATYPE_IN, ASCENDC_TPL_UI_LIST, DEFINED_DT_FLOAT16, DEFINED_DT_BF16),
        ASCENDC_TPL_UINT_SEL(DATATYPE_OUT, ASCENDC_TPL_UI_LIST, DEFINED_DT_FLOAT16, DEFINED_DT_BF16),
        ASCENDC_TPL_UINT_SEL(KERNEL_TYPE, ASCENDC_TPL_UI_LIST, MULTICORE_SPLITK_MATMUL),
        ASCENDC_TPL_UINT_SEL(PADDING_TAGA, ASCENDC_TPL_UI_LIST, DEFINED_PADDING_NONE, DEFINED_PADDING_NZ),
        ASCENDC_TPL_UINT_SEL(PADDING_TAGB, ASCENDC_TPL_UI_LIST, DEFINED_PADDING_NONE, DEFINED_PADDING_NZ),
        ASCENDC_TPL_UINT_SEL(PADDING_TAGC, ASCENDC_TPL_UI_LIST, DEFINED_PADDING_NONE),
        ASCENDC_TPL_UINT_SEL(LAYOUT_TAGA, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
        ASCENDC_TPL_UINT_SEL(LAYOUT_TAGB, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
        ASCENDC_TPL_UINT_SEL(LAYOUT_TAGC, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
        ASCENDC_TPL_UINT_SEL(DISPATCH_POLICY_TAG, ASCENDC_TPL_UI_LIST, MATMUL_AIV_DEFAULT),
    ),
    // streamk matmul
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(DATATYPE_IN, ASCENDC_TPL_UI_LIST, DEFINED_DT_FLOAT16, DEFINED_DT_BF16),
        ASCENDC_TPL_UINT_SEL(DATATYPE_OUT, ASCENDC_TPL_UI_LIST, DEFINED_DT_FLOAT16, DEFINED_DT_BF16),
        ASCENDC_TPL_UINT_SEL(KERNEL_TYPE, ASCENDC_TPL_UI_LIST, STREAMK_MATMUL),
        ASCENDC_TPL_UINT_SEL(PADDING_TAGA, ASCENDC_TPL_UI_LIST, DEFINED_PADDING_NONE, DEFINED_PADDING_NZ),
        ASCENDC_TPL_UINT_SEL(PADDING_TAGB, ASCENDC_TPL_UI_LIST, DEFINED_PADDING_NONE, DEFINED_PADDING_NZ),
        ASCENDC_TPL_UINT_SEL(PADDING_TAGC, ASCENDC_TPL_UI_LIST, DEFINED_PADDING_NONE),
        ASCENDC_TPL_UINT_SEL(LAYOUT_TAGA, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
        ASCENDC_TPL_UINT_SEL(LAYOUT_TAGB, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
        ASCENDC_TPL_UINT_SEL(LAYOUT_TAGC, ASCENDC_TPL_UI_LIST, DEFINED_ROW_MAJOR, DEFINED_COLUMN_MAJOR),
        ASCENDC_TPL_UINT_SEL(DISPATCH_POLICY_TAG, ASCENDC_TPL_UI_LIST, MATMUL_AIV_DEFAULT),
    ),
);

#endif // __CATLASS_DYNAMIC_MATMUL_TILING_KEY_H__